// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package cn.yusei.ib.socket;

public final class Network {
  private Network() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.yusei.ib.socket.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
     */
    cn.yusei.ib.socket.Network.Message.MessageType getType();

    /**
     * <code>int64 time = 2;</code>
     */
    long getTime();

    /**
     * <code>string token = 3;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>int32 from = 4;</code>
     */
    int getFrom();

    /**
     * <code>int32 to = 5;</code>
     */
    int getTo();

    /**
     * <code>string data = 6;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 6;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code cn.yusei.ib.socket.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.yusei.ib.socket.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      time_ = 0L;
      token_ = "";
      from_ = 0;
      to_ = 0;
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              time_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 32: {

              from_ = input.readInt32();
              break;
            }
            case 40: {

              to_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.yusei.ib.socket.Network.internal_static_cn_yusei_ib_socket_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.yusei.ib.socket.Network.internal_static_cn_yusei_ib_socket_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.yusei.ib.socket.Network.Message.class, cn.yusei.ib.socket.Network.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code cn.yusei.ib.socket.Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RESPONSE = 0;</code>
       */
      RESPONSE(0),
      /**
       * <code>LOGIN = 1;</code>
       */
      LOGIN(1),
      /**
       * <code>LOGOUT = 2;</code>
       */
      LOGOUT(2),
      /**
       * <code>LINK_REQUEST = 3;</code>
       */
      LINK_REQUEST(3),
      /**
       * <code>LINK_ADMIT = 4;</code>
       */
      LINK_ADMIT(4),
      /**
       * <code>LINK_REJECT = 5;</code>
       */
      LINK_REJECT(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RESPONSE = 0;</code>
       */
      public static final int RESPONSE_VALUE = 0;
      /**
       * <code>LOGIN = 1;</code>
       */
      public static final int LOGIN_VALUE = 1;
      /**
       * <code>LOGOUT = 2;</code>
       */
      public static final int LOGOUT_VALUE = 2;
      /**
       * <code>LINK_REQUEST = 3;</code>
       */
      public static final int LINK_REQUEST_VALUE = 3;
      /**
       * <code>LINK_ADMIT = 4;</code>
       */
      public static final int LINK_ADMIT_VALUE = 4;
      /**
       * <code>LINK_REJECT = 5;</code>
       */
      public static final int LINK_REJECT_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return RESPONSE;
          case 1: return LOGIN;
          case 2: return LOGOUT;
          case 3: return LINK_REQUEST;
          case 4: return LINK_ADMIT;
          case 5: return LINK_REJECT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.yusei.ib.socket.Network.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.yusei.ib.socket.Message.MessageType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
     */
    public cn.yusei.ib.socket.Network.Message.MessageType getType() {
      @SuppressWarnings("deprecation")
      cn.yusei.ib.socket.Network.Message.MessageType result = cn.yusei.ib.socket.Network.Message.MessageType.valueOf(type_);
      return result == null ? cn.yusei.ib.socket.Network.Message.MessageType.UNRECOGNIZED : result;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <code>int64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 3;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 4;
    private int from_;
    /**
     * <code>int32 from = 4;</code>
     */
    public int getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 5;
    private int to_;
    /**
     * <code>int32 to = 5;</code>
     */
    public int getTo() {
      return to_;
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 6;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != cn.yusei.ib.socket.Network.Message.MessageType.RESPONSE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (time_ != 0L) {
        output.writeInt64(2, time_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      if (from_ != 0) {
        output.writeInt32(4, from_);
      }
      if (to_ != 0) {
        output.writeInt32(5, to_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != cn.yusei.ib.socket.Network.Message.MessageType.RESPONSE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, time_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, from_);
      }
      if (to_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, to_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.yusei.ib.socket.Network.Message)) {
        return super.equals(obj);
      }
      cn.yusei.ib.socket.Network.Message other = (cn.yusei.ib.socket.Network.Message) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getTime()
          == other.getTime());
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getFrom()
          == other.getFrom());
      result = result && (getTo()
          == other.getTo());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.yusei.ib.socket.Network.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.yusei.ib.socket.Network.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.yusei.ib.socket.Network.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.yusei.ib.socket.Network.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.yusei.ib.socket.Network.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.yusei.ib.socket.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.yusei.ib.socket.Message)
        cn.yusei.ib.socket.Network.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.yusei.ib.socket.Network.internal_static_cn_yusei_ib_socket_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.yusei.ib.socket.Network.internal_static_cn_yusei_ib_socket_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.yusei.ib.socket.Network.Message.class, cn.yusei.ib.socket.Network.Message.Builder.class);
      }

      // Construct using cn.yusei.ib.socket.Network.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        time_ = 0L;

        token_ = "";

        from_ = 0;

        to_ = 0;

        data_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.yusei.ib.socket.Network.internal_static_cn_yusei_ib_socket_Message_descriptor;
      }

      @java.lang.Override
      public cn.yusei.ib.socket.Network.Message getDefaultInstanceForType() {
        return cn.yusei.ib.socket.Network.Message.getDefaultInstance();
      }

      @java.lang.Override
      public cn.yusei.ib.socket.Network.Message build() {
        cn.yusei.ib.socket.Network.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.yusei.ib.socket.Network.Message buildPartial() {
        cn.yusei.ib.socket.Network.Message result = new cn.yusei.ib.socket.Network.Message(this);
        result.type_ = type_;
        result.time_ = time_;
        result.token_ = token_;
        result.from_ = from_;
        result.to_ = to_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.yusei.ib.socket.Network.Message) {
          return mergeFrom((cn.yusei.ib.socket.Network.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.yusei.ib.socket.Network.Message other) {
        if (other == cn.yusei.ib.socket.Network.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0) {
          setTo(other.getTo());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.yusei.ib.socket.Network.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.yusei.ib.socket.Network.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
       */
      public cn.yusei.ib.socket.Network.Message.MessageType getType() {
        @SuppressWarnings("deprecation")
        cn.yusei.ib.socket.Network.Message.MessageType result = cn.yusei.ib.socket.Network.Message.MessageType.valueOf(type_);
        return result == null ? cn.yusei.ib.socket.Network.Message.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
       */
      public Builder setType(cn.yusei.ib.socket.Network.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.yusei.ib.socket.Message.MessageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 2;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 3;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int from_ ;
      /**
       * <code>int32 from = 4;</code>
       */
      public int getFrom() {
        return from_;
      }
      /**
       * <code>int32 from = 4;</code>
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 from = 4;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int to_ ;
      /**
       * <code>int32 to = 5;</code>
       */
      public int getTo() {
        return to_;
      }
      /**
       * <code>int32 to = 5;</code>
       */
      public Builder setTo(int value) {
        
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 to = 5;</code>
       */
      public Builder clearTo() {
        
        to_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 6;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 6;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 6;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 6;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.yusei.ib.socket.Message)
    }

    // @@protoc_insertion_point(class_scope:cn.yusei.ib.socket.Message)
    private static final cn.yusei.ib.socket.Network.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.yusei.ib.socket.Network.Message();
    }

    public static cn.yusei.ib.socket.Network.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.yusei.ib.socket.Network.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_yusei_ib_socket_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_yusei_ib_socket_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rNetwork.proto\022\022cn.yusei.ib.socket\"\354\001\n\007" +
      "Message\0225\n\004type\030\001 \001(\0162\'.cn.yusei.ib.sock" +
      "et.Message.MessageType\022\014\n\004time\030\002 \001(\003\022\r\n\005" +
      "token\030\003 \001(\t\022\014\n\004from\030\004 \001(\005\022\n\n\002to\030\005 \001(\005\022\014\n" +
      "\004data\030\006 \001(\t\"e\n\013MessageType\022\014\n\010RESPONSE\020\000" +
      "\022\t\n\005LOGIN\020\001\022\n\n\006LOGOUT\020\002\022\020\n\014LINK_REQUEST\020" +
      "\003\022\016\n\nLINK_ADMIT\020\004\022\017\n\013LINK_REJECT\020\005b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_yusei_ib_socket_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_yusei_ib_socket_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_yusei_ib_socket_Message_descriptor,
        new java.lang.String[] { "Type", "Time", "Token", "From", "To", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
